### ISSUE TITLE
Unsolvable words with double-cased letters

### ISSUE THREAD

**Issue by johnnyhoffman** [despo/hangman#3]
Hi I ran into a circumstance where a word is unsolvable. It happens when a word contains both an upper-case and lower-case version of the same letter, e.g. `C` and `c` in **C**apri**c**orn. 

Guessing either `c` or `C` both result in `C________`. Continuing to choose the alternative in a subsequent guess, a 304 is returned due to a _repeat guess_. This means that the lower case `c` can never be uncovered.

**Comment by chiefsmurph** [comment]
I would like to confirm that I am receiving this same issue.
Using the same word list...

```
Tetrao
----------------
num possible: 17706
letter e true _e____
num possible: 1425
letter r true _e_r__
num possible: 56
letter a true _e_ra_
num possible: 14
letter b false _e_ra_
num possible: 6
letter t true Te_ra_
num possible: 0
hint
letter null true Te_ra_
num possible: 0
hint
{"solution":"Tetrao","token":"eyJzb2x1dGlvbiI6IlRldHJhbyIsImNvcnJlY3RfZ3Vlc3NlcyI6W10sIndyb25nX2d1ZXNzZXMiOltdfQ=="}
```
